### ISSUE TITLE
Could you provide some parts of the data?

### ISSUE THREAD

**Issue by GuangChen2016** [marekrei/sequence-labeler#1]
@marekrei Hello, marekrei. It's very nice work, and I want to reproduce your work. But I have some problem in preparing the required format. So could you please provide some parts of the data for me? Thank you very much.

**Comment by marekrei** [comment]
Hi @GuangChen2016 
I'm in the process of releasing the error detection dataset. It should be online by next week.
Until then, the input files should look like this:

    This        c
    is          c
    an          i
    sentence    c

In this case the task is error detection and there are two possible labels - c and i. But you can replace that with POS tags, NER tags, etc. Make sure to leave an empty line between sentences.
I hope this helps.

**Comment by GuangChen2016** [comment]
@marekrei Thank you.

**Comment by liuyichaosoftware** [comment]
hi marekrei, I would like to reproduce your work, but I have a problem to get the FCE data, could you please give me a help with the data? thank you very much.

**Comment by marekrei** [comment]
The error detection data is now available here:
http://www.ilexir.co.uk/datasets/index.html

You might also be interested in the blog post I wrote about this topic:
http://www.marekrei.com/blog/attending-to-characters-in-neural-sequence-labeling-models/

**Comment by liuyichaosoftware** [comment]
thank you very much~
