### ISSUE TITLE
Using model on new data

### ISSUE THREAD

**Issue by Slyfest** [marekrei/sequence-labeler#2]
Hello, @marekrei 
Great work!
I’m trying to make use of bidirectional lstm for binary sequence labeling.
Having trained your model on my data, i want to
test it on separate sentence, presumably, not from the training set.

In other words, how to use trained model to get output for one sentence at a time?

**Comment by marekrei** [comment]
Hi @Slyfest ,

The code doesn't currently have an out-of-the-box functionality for saving an output file, just running and evaluating an experiment. I'll add that functionality in the next update.
In the mean time, you could create it yourself either by integrating a saving functionality in process_batches() or creating a separate script that loads a saved model, processes a file and prints the results.

**Comment by Slyfest** [comment]
Thanks for your reply!
I will work in this direction

**Comment by marekrei** [comment]
There is now a script for printing output for any input file.
