### ISSUE TITLE
Possible wrong lowercase flag is passed?

### ISSUE THREAD

**Issue by kmkurn** [marekrei/sequence-labeler#7]
Hi,

Did you mean to pass `lowercase_chars` flag when building characters vocabulary here?

https://github.com/marekrei/sequence-labeler/blob/484a6beb1e2a2cccaac74ce717b1ee30c79fc8d8/sequence_labeling_experiment.py#L285

**Comment by marekrei** [comment]
Indeed, thanks for catching that!
I've actually created a new version that removes the option of lowercasing characters, as that's not really needed. Will update soon.
